# Generated by Django 3.0.8 on 2020-09-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200926_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='memeo',
            new_name='memo',
        ),
    ]
